const KEY='familiemat-v1-data';
const days=['Mandag','Tirsdag','Onsdag','Torsdag','Fredag','Lørdag','Søndag'];
const starterRecipes=[
{name:'Spaghetti bolognese',servings:4,ingredients:[['Kjøttdeig',400,'g'],['Spaghetti',500,'g'],['Løk',1,'stk'],['Hakkede tomater',2,'bokser']],instructions:'Stek kjøttdeig og løk. Tilsett tomater og la sausen småkoke. Kok pasta og server.',url:''},
{name:'Taco',servings:4,ingredients:[['Kjøttdeig',400,'g'],['Løk',1,'stk'],['Tacokrydder',1,'pose'],['Tortilla',1,'pakke'],['Mais',1,'boks'],['Salsa',1,'glass']],instructions:'Stek kjøttdeig og løk. Tilsett krydder og server med tilbehør.',url:''},
{name:'Laks med poteter',servings:4,ingredients:[['Laks',600,'g'],['Poteter',1,'kg'],['Sitron',1,'stk'],['Rømme',2,'dl']],instructions:'Stek eller bak laksen. Kok poteter og server med sitron og rømme.',url:''},
{name:'Kyllinggryte',servings:4,ingredients:[['Kylling',600,'g'],['Løk',1,'stk'],['Paprika',1,'stk'],['Kokosmelk',1,'boks'],['Ris',300,'g']],instructions:'Stek kylling og grønnsaker. Tilsett kokosmelk og la gryten småkoke. Server med ris.',url:''},
{name:'Hjemmelaget pizza',servings:4,ingredients:[['Pizzabunn',1,'stk'],['Pizzasaus',1,'glass'],['Ost',300,'g'],['Skinke',200,'g']],instructions:'Fordel saus og topping på bunnen. Stek til osten er gyllen.',url:''},
{name:'Fiskekaker med poteter',servings:4,ingredients:[['Fiskekaker',8,'stk'],['Poteter',1,'kg'],['Gulrøtter',4,'stk'],['Smør',50,'g']],instructions:'Kok poteter og gulrøtter. Stek fiskekakene og server med smør.',url:''}
];
const starterPantry=['Mel','Sukker','Salt','Pepper','Olje','Smør','Kaffe','Ris','Pasta','Havregryn','Ketchup','Oppvaskmiddel','Toalettpapir'].map(name=>({name,low:false}));
let data=load(); let page='week';
function load(){try{let x=JSON.parse(localStorage.getItem(KEY));if(x)return x}catch(e){}return{week:Array(7).fill(null),recipes:starterRecipes,pantry:starterPantry,shopping:[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
const categoryOrder=['Frukt og grønt','Kjøtt og fisk','Meieri og egg','Brød og bakervarer','Tørrvarer','Hermetikk og sauser','Frysevarer','Drikke','Husholdning','Annet'];
function sortShopping(){data.shopping=(data.shopping||[]).map(x=>({...x,category:categorizeIngredient(x.name)})).sort((a,b)=>{const ca=categoryOrder.indexOf(a.category),cb=categoryOrder.indexOf(b.category);return (ca-cb)||String(a.name).localeCompare(String(b.name),'nb',{sensitivity:'base'})});}
sortShopping();
syncShopping();
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){document.getElementById('app').innerHTML=`<div class="app"><header class="top"><div><div class="brand">🍲 Familiemat</div><div class="subtitle">Middag, basisvarer og handleliste samlet.</div></div></header><main class="content">${page==='week'?weekView():page==='recipes'?recipesView():page==='shopping'?shoppingView():pantryView()}</main><nav class="nav"><div class="navinner">${nav('week','🏠','Uke')}${nav('recipes','🍝','Oppskrifter')}${nav('shopping','🛒','Handleliste')}${nav('pantry','🧺','Basisvarer')}</div></nav></div>`}
function nav(p,i,t){return `<button class="${page===p?'active':''}" onclick="go('${p}')"><span class="ico">${i}</span>${t}</button>`}
function go(p){page=p;render();window.scrollTo(0,0)}
function weekView(){return `<div class="section-title">Denne uka</div>${data.week.map((r,i)=>`<div class="card day"><div class="dayname">${days[i]}</div>${r?`<div class="meal"><strong>${esc(r)}</strong><small>${esc(data.recipes.find(x=>x.name===r)?.servings||4)} porsjoner</small></div><button class="btn secondary" onclick="choose(${i})">Bytt</button>`:`<div class="meal"><strong>Ingen middag valgt</strong><small>Hva skal dere spise?</small></div><button class="btn" onclick="choose(${i})">Velg</button>`}</div>`).join('')}<div class="card"><strong>Tips</strong><p class="small">Handlelisten slår sammen like ingredienser fra alle middagene. Basisvarer du markerer som «går tom» blir også lagt til.</p></div>`}
function recipesView(){return `<div class="section-title">Oppskrifter</div><button class="btn full" onclick="newRecipe()">＋ Ny oppskrift</button><button class="btn full secondary" onclick="webRecipe()">🌐 Oppskrift fra nett</button>${data.recipes.map((r,i)=>`<div class="card"><div class="recipe-head"><div><div class="recipe-title">${esc(r.name)}</div><div class="small">${r.servings} porsjoner</div></div>${r.url?`<a class="pill" href="${esc(r.url)}" target="_blank">Nettlenke</a>`:''}</div><ul class="ingredients">${r.ingredients.map(x=>`<li>${esc(x[1])} ${esc(x[2])} ${esc(x[0])}</li>`).join('')}</ul><div class="actions"><button class="btn" onclick="addRecipeToWeek(${i})">＋ Legg til i uka</button><button class="btn secondary" onclick="editRecipe(${i})">Rediger</button><button class="btn ghost" onclick="deleteRecipe(${i})">Slett</button></div></div>`).join('')}`}
function shoppingView(){sortShopping();save();const items=data.shopping;let bought=items.filter(x=>x.done).length;const groups={};items.forEach((x,i)=>{const cat=x.category||categorizeIngredient(x.name);if(!groups[cat])groups[cat]=[];groups[cat].push({...x,index:i})});const ordered=Object.keys(groups).sort((a,b)=>categoryOrder.indexOf(a)-categoryOrder.indexOf(b));return `<div class=\"section-title\">Handleliste</div><div class=\"card\"><strong>${bought} av ${items.length} varer kjøpt</strong><div class=\"progress\" style=\"margin-top:10px\"><div style=\"width:${items.length?bought/items.length*100:0}%\"></div></div><p class=\"small\" style=\"margin-bottom:0\">Sortert etter butikkategori og alfabetisk.</p></div>${items.length?ordered.map(cat=>`<div class=\"shop-category\"><h3>${esc(cat)}</h3><div class=\"list\">${groups[cat].map(x=>`<label class=\"row ${x.done?'done':''}\"><input type=\"checkbox\" ${x.done?'checked':''} onchange=\"toggleShop(${x.index})\"><span>${esc(x.name)}</span><span class=\"qty\">${esc(formatQty(x.qty))} ${esc(x.unit)}</span></label>`).join('')}</div></div>`).join('')+`<button class=\"btn full secondary\" onclick=\"clearBought()\">Fjern kjøpte varer</button>`:`<div class=\"empty\">Handlelisten er tom.<br>Legg til middager eller marker basisvarer som «går tom».</div>`}`}
function categorizeIngredient(name){const n=String(name||'').trim().toLowerCase();const exact={'poteter':'Frukt og grønt','gulrøtter':'Frukt og grønt','gulrot':'Frukt og grønt','løk':'Frukt og grønt','paprika':'Frukt og grønt','sitron':'Frukt og grønt','tomat':'Frukt og grønt','agurk':'Frukt og grønt','salat':'Frukt og grønt','brokkoli':'Frukt og grønt','blomkål':'Frukt og grønt','eple':'Frukt og grønt','banan':'Frukt og grønt','avokado':'Frukt og grønt','hvitløk':'Frukt og grønt','ingefær':'Frukt og grønt','laks':'Kjøtt og fisk','fiskekaker':'Kjøtt og fisk','fiskekake':'Kjøtt og fisk','torsk':'Kjøtt og fisk','kjøttdeig':'Kjøtt og fisk','kylling':'Kjøtt og fisk','skinke':'Kjøtt og fisk','bacon':'Kjøtt og fisk','pølse':'Kjøtt og fisk','karbonade':'Kjøtt og fisk','rømme':'Meieri og egg','ost':'Meieri og egg','smør':'Meieri og egg','melk':'Meieri og egg','yoghurt':'Meieri og egg','fløte':'Meieri og egg','egg':'Meieri og egg','kremost':'Meieri og egg','parmesan':'Meieri og egg','mozzarella':'Meieri og egg','feta':'Meieri og egg','spaghetti':'Tørrvarer','pasta':'Tørrvarer','ris':'Tørrvarer','havregryn':'Tørrvarer','mel':'Tørrvarer','sukker':'Tørrvarer','salt':'Tørrvarer','pepper':'Tørrvarer','olje':'Tørrvarer','kaffe':'Tørrvarer','te':'Tørrvarer','tacokrydder':'Tørrvarer','krydder':'Tørrvarer','tortilla':'Tørrvarer','melis':'Tørrvarer','bakepulver':'Tørrvarer','hakkede tomater':'Hermetikk og sauser','kokosmelk':'Hermetikk og sauser','mais':'Hermetikk og sauser','salsa':'Hermetikk og sauser','bønner':'Hermetikk og sauser','pizzasaus':'Hermetikk og sauser','brød':'Brød og bakervarer','rundstykker':'Brød og bakervarer','rundstykke':'Brød og bakervarer','knekkebrød':'Brød og bakervarer','baguette':'Brød og bakervarer','pizzabunn':'Brød og bakervarer','iskrem':'Frysevarer','juice':'Drikke','brus':'Drikke','vann':'Drikke','saft':'Drikke','toalettpapir':'Husholdning','oppvaskmiddel':'Husholdning','såpe':'Husholdning','vaskemiddel':'Husholdning','tørkepapir':'Husholdning','servietter':'Husholdning'};if(exact[n])return exact[n];if(/frossen|fryse|iskrem/.test(n))return 'Frysevarer';if(/toalett|dopapir|oppvask|såpe|vask|tørkepapir|serviett/.test(n))return 'Husholdning';if(/juice|brus|vann|saft/.test(n))return 'Drikke';if(/kokosmelk|mais|salsa|bønne|hakkede tomater|hermet|glass|boks/.test(n))return 'Hermetikk og sauser';if(/brød|rundstykke|knekkebrød|baguette|pizzabunn/.test(n))return 'Brød og bakervarer';if(/kjøtt|kjøttdeig|kylling|skinke|bacon|pølse|laks|fisk|fiskekake|torsk|karbonade/.test(n))return 'Kjøtt og fisk';if(/melk|rømme|ost|smør|yoghurt|fløte|egg|kremost|parmesan|mozzarella|feta/.test(n))return 'Meieri og egg';if(/spaghetti|pasta|ris|havre|mel|sukker|salt|pepper|olje|kaffe|te|tacokrydder|krydder|tortilla|melis|bakepulver/.test(n))return 'Tørrvarer';if(/potet|løk|paprika|gulrot|sitron|tomat|agurk|salat|brokkoli|blomkål|eple|banan|avokado|hvitløk|ingefær/.test(n))return 'Frukt og grønt';return 'Annet'}
function pantryView(){const items=[...data.pantry].sort((a,b)=>String(a.name).localeCompare(String(b.name),'nb',{sensitivity:'base'}));return `<div class="section-title">Basisvarer</div><p class="small">Marker det dere begynner å gå tom for. Da havner varen automatisk på handlelisten.</p><button class="btn full" onclick="addPantry()">＋ Legg til basisvare</button><div class="list" style="margin-top:10px">${items.map(x=>{const i=data.pantry.indexOf(x);return `<label class="row"><input type="checkbox" ${x.low?'checked':''} onchange="togglePantry(${i})"><span>${esc(x.name)}</span><span class="qty">${x.low?'Går tom':'Har hjemme'}</span></label>`}).join('')}</div>`}
function choose(day){modal(`<h2>Velg middag – ${days[day]}</h2><p class="small">Trykk på en oppskrift for å legge den direkte inn på ${days[day].toLowerCase()}.</p><div class="list">${data.recipes.map((r,i)=>`<button type="button" class="row recipe-choice" onclick="setDay(${day},${i})"><span>🍽️</span><span style="flex:1;text-align:left"><strong>${esc(r.name)}</strong><small style="display:block;color:var(--muted)">${esc(r.servings)} porsjoner</small></span><span>›</span></button>`).join('')}</div><button type="button" class="btn full secondary" onclick="newRecipeForDay(${day})">＋ Lag ny oppskrift</button>`)}
function setDay(d,recipeIndex){const r=data.recipes[recipeIndex];if(!r)return;data.week[d]=r.name;syncShopping();save();closeModal();render()}
function addRecipeToWeek(recipeIndex){const r=data.recipes[recipeIndex];if(!r)return;modal(`<h2>Legg «${esc(r.name)}» til i uka</h2><p class="small">Velg hvilken dag middagen skal være.</p><div class="list">${days.map((d,i)=>`<button type="button" class="row" style="text-align:left" onclick="setDay(${i},${recipeIndex})"><span>📅</span><strong>${d}</strong>${data.week[i]===r.name?'<span class="qty">Valgt</span>':''}</button>`).join('')}</div>`)}
function newRecipeForDay(day){closeModal();recipeForm(-1,day)}
function syncShopping(){const old=new Map((data.shopping||[]).map(x=>[x.name.trim().toLowerCase(),x]));const map=new Map();for(const name of data.week.filter(Boolean)){const r=data.recipes.find(x=>x.name===name);if(!r)continue;for(const [ing,q,u] of r.ingredients){const k=ing.trim().toLowerCase();if(!map.has(k))map.set(k,{name:ing,qty:0,unit:u,category:categorizeIngredient(ing),done:old.get(k)?.done||false});const x=map.get(k);x.category=categorizeIngredient(x.name);if(x.unit===u&&typeof q==='number')x.qty+=q;else if(x.qty===0){x.qty=q;x.unit=u}}}for(const p of data.pantry.filter(x=>x.low)){const k=p.name.trim().toLowerCase();if(!map.has(k))map.set(k,{name:p.name,qty:1,unit:'stk',category:categorizeIngredient(p.name),done:old.get(k)?.done||false})}data.shopping=[...map.values()].sort((a,b)=>{const ca=categoryOrder.indexOf(a.category),cb=categoryOrder.indexOf(b.category);return (ca-cb)||String(a.name).localeCompare(String(b.name),'nb',{sensitivity:'base'})});save()}
function buildShopping(){syncShopping();page='shopping';render()}
function formatQty(q){return Number.isInteger(q)?q:String(Math.round(q*100)/100)}
function toggleShop(i){data.shopping[i].done=!data.shopping[i].done;const item=data.shopping[i];const pantry=data.pantry.find(p=>p.name.trim().toLowerCase()===item.name.trim().toLowerCase());if(pantry&&item.done)pantry.low=false;save();render()}
function clearBought(){data.shopping=data.shopping.filter(x=>!x.done);save();render()}
function togglePantry(i){data.pantry[i].low=!data.pantry[i].low;syncShopping();render()}
function addPantry(){modal(`<h2>Ny basisvare</h2><div class="field"><label>Navn</label><input id="pname" placeholder="F.eks. melk"></div><button class="btn full" onclick="savePantry()">Legg til</button>`)}
function savePantry(){let n=document.getElementById('pname').value.trim();if(!n)return;data.pantry.push({name:n,low:false});save();closeModal();render()}
function recipeForm(i=-1,day=null,prefill=null){const r=prefill||(i>=0?data.recipes[i]:{name:'',servings:4,ingredients:[['',1,'stk']],instructions:'',url:''});modal(`<h2>${i>=0?'Rediger oppskrift':(prefill?'Importer oppskrift':'Ny oppskrift')}</h2>${prefill?'<p class="small">Vi har hentet innholdet fra nettsiden. Gå gjennom ingrediensene før du lagrer — du kan endre, slette og legge til akkurat som i en vanlig oppskrift.</p>':''}<div class="field"><label>Navn</label><input id="rname" value="${esc(r.name)}"></div><div class="field"><label>Porsjoner</label><input id="rserv" type="number" value="${r.servings}"></div><div class="field"><label>Ingredienser</label><div id="ings">${r.ingredients.map((x,j)=>ingRow(x,j)).join('')}</div><button class="btn secondary" onclick="addIng()">＋ Ingrediens</button></div><div class="field"><label>Fremgangsmåte</label><textarea id="rinst" rows="5">${esc(r.instructions)}</textarea></div><div class="field"><label>Lenke (valgfritt)</label><input id="rurl" type="url" value="${esc(r.url)}" placeholder="https://..."></div><button class="btn full" onclick="saveRecipe(${i},${day===null?'null':day})">Lagre oppskrift</button>`)}
function ingRow(x,j){return `<div class="ingredient-edit" data-i="${j}"><input class="in" value="${esc(x[0])}" placeholder="Vare"><input class="iq" type="number" step="0.01" value="${x[1]}"><input class="iu" value="${esc(x[2])}" placeholder="enhet"><button class="btn danger" onclick="this.parentElement.remove()">×</button></div>`}
function addIng(){document.getElementById('ings').insertAdjacentHTML('beforeend',ingRow(['',1,'stk'],Date.now()))}
function saveRecipe(i,day=null){const ings=[...document.querySelectorAll('#ings .ingredient-edit')].map(el=>[el.querySelector('.in').value.trim(),Number(el.querySelector('.iq').value)||0,el.querySelector('.iu').value.trim()]).filter(x=>x[0]);const r={name:document.getElementById('rname').value.trim(),servings:Number(document.getElementById('rserv').value)||4,ingredients:ings,instructions:document.getElementById('rinst').value,url:document.getElementById('rurl').value.trim()};if(!r.name||!ings.length)return alert('Fyll inn navn og minst én ingrediens.');if(i<0){data.recipes.push(r);if(day!==null)data.week[day]=r.name}else data.recipes[i]=r;syncShopping();save();closeModal();render()}
function newRecipe(){recipeForm()};function editRecipe(i){recipeForm(i)}
function deleteRecipe(i){if(confirm('Slette oppskriften?')){data.recipes.splice(i,1);data.week=data.week.map(x=>data.recipes.some(r=>r.name===x)?x:null);syncShopping();save();render()}}
function webRecipe(){modal(`<h2>🌐 Oppskrift fra nett</h2><p class="small">Lim inn lenken til en oppskrift. Familiemat prøver å hente navn, porsjoner, ingredienser og fremgangsmåte automatisk. Du får redigere alt før du lagrer.</p><div class="field"><label>Lenke til oppskrift</label><input id="weburl" type="url" inputmode="url" placeholder="https://..."></div><button class="btn full" onclick="importWebRecipe()">Hent oppskrift</button><p class="small">Tips: Oppskrifter som bruker standarden Schema.org/Recipe gir som regel best resultat. cite_placeholder</p>`)}

function parseImportedIngredient(line){let t=String(line||'').replace(/^[-*•]\s*/,'').replace(/\s+/g,' ').trim();if(!t)return null; t=t.replace(/^\d+\.\s*/, '');
 const m=t.match(/^(?:ca\.?\s*)?([0-9]+(?:[,.][0-9]+)?|[½¼¾⅓⅔⅛⅜⅝⅞])\s*(stk\.?|kg|g|mg|l|dl|cl|ml|ss|ts|pk|pose|poser|boks|bokser|glass|beger|pakke|pakker|skive|skiver|fedd|båt|båter|potte|krukke|flaske|liter|kg)?\s*(.*)$/i);
 if(m){let q=m[1].replace(',','.');const fractions={'½':.5,'¼':.25,'¾':.75,'⅓':1/3,'⅔':2/3,'⅛':.125,'⅜':.375,'⅝':.625,'⅞':.875};q=fractions[q]??Number(q);let unit=(m[2]||'stk').replace('.','');let name=m[3].trim().replace(/^av\s+/i,'');if(name)return [name,q,unit];}
 return [t,1,'stk'];}

function parseRecipeMarkdown(text){const lines=String(text||'').split(/\r?\n/);let title='',servings=4,ingredients=[],instructions=[];const heading=(s)=>s.replace(/^#+\s*/,'').trim().toLowerCase();
 for(const line of lines){const h=heading(line);if(!title&&line.trim()&&!/^#/.test(line)&&line.trim().length<120){/* title is normally supplied by Reader JSON */}}
 let start=-1,end=lines.length;for(let i=0;i<lines.length;i++){const h=heading(lines[i]);if(/^(ingredienser|ingredients)$/.test(h)){start=i+1;break;}}if(start>=0){for(let i=start;i<lines.length;i++){const h=heading(lines[i]);if(/^#{1,6}\s*/.test(lines[i])&&i>start){end=i;break;}if(/^(næringsinnhold|nutrition|slik gjør du|fremgangsmåte|instructions)$/.test(h)){end=i;break;}const raw=lines[i].trim();if(!raw||/^porsjoner$/i.test(raw)||/^porsjoner/i.test(raw))continue;if(/^[-*•]/.test(raw))ingredients.push(parseImportedIngredient(raw));}}
 let istart=-1;for(let i=0;i<lines.length;i++){const h=heading(lines[i]);if(/^(slik gjør du|fremgangsmåte|instructions)$/.test(h)){istart=i+1;break;}}if(istart>=0){for(let i=istart;i<lines.length;i++){if(/^#{1,6}\s*/.test(lines[i]))break;const raw=lines[i].trim();if(raw)instructions.push(raw.replace(/^\d+[.)]\s*/,''));}}
 const servingsMatch=String(text).match(/(?:porsjoner|servings?)\s*[:|]?\s*(\d+)/i);if(servingsMatch)servings=Number(servingsMatch[1])||4;return {servings,ingredients:ingredients.filter(Boolean),instructions:instructions.join('\n')};}

async function importWebRecipe(){const input=document.getElementById('weburl');const url=(input?.value||'').trim();if(!/^https?:\/\//i.test(url))return alert('Lim inn en gyldig nettadresse som starter med https:// eller http://.');const btn=document.querySelector('#modal .sheet .btn.full');if(btn){btn.disabled=true;btn.textContent='Henter oppskrift…';}try{const reader='https://r.jina.ai/'+url;const res=await fetch(reader,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error('Reader HTTP '+res.status);const raw=await res.text();let payload;try{payload=JSON.parse(raw)}catch{payload={data:{content:raw}}}const d=payload.data||payload;const content=d.content||raw;const parsed=parseRecipeMarkdown(content);let name=d.title||'';if(!name){const m=content.match(/^#\s+(.+)$/m);name=m?m[1].trim():''}if(!parsed.ingredients.length)throw new Error('Fant ingen ingredienser på siden.');recipeForm(-1,null,{name:name||'Importert oppskrift',servings:parsed.servings||4,ingredients:parsed.ingredients,instructions:parsed.instructions,url});}catch(err){console.error(err);alert('Jeg klarte ikke å hente ingrediensene automatisk fra denne siden. Nettstedet kan blokkere import, eller oppskriften kan bruke en struktur Familiemat ikke kjenner igjen ennå. Du kan fortsatt legge inn oppskriften manuelt.');}finally{if(btn){btn.disabled=false;btn.textContent='Hent oppskrift';}}}
function modal(inner){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal" onclick="if(event.target.id==='modal')closeModal()"><div class="sheet">${inner}<button class="btn full secondary" onclick="closeModal()">Avbryt</button></div></div>`)}
function closeModal(){document.getElementById('modal')?.remove()}
window.go=go;window.choose=choose;window.setDay=setDay;window.addRecipeToWeek=addRecipeToWeek;window.newRecipeForDay=newRecipeForDay;window.buildShopping=buildShopping;window.toggleShop=toggleShop;window.clearBought=clearBought;window.togglePantry=togglePantry;window.addPantry=addPantry;window.savePantry=savePantry;window.newRecipe=newRecipe;window.editRecipe=editRecipe;window.deleteRecipe=deleteRecipe;window.webRecipe=webRecipe;window.importWebRecipe=importWebRecipe;window.recipeForm=recipeForm;window.addIng=addIng;window.saveRecipe=saveRecipe;window.closeModal=closeModal;
if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});render();
