const KEY='familiemat-v1-data';
const days=['Mandag','Tirsdag','Onsdag','Torsdag','Fredag','Lørdag','Søndag'];
const starterRecipes=[
{name:'Spaghetti bolognese',servings:4,ingredients:[['Kjøttdeig',400,'g'],['Spaghetti',500,'g'],['Løk',1,'stk'],['Hakkede tomater',2,'bokser']],instructions:'Stek kjøttdeig og løk. Tilsett tomater og la sausen småkoke. Kok pasta og server.',url:''},
{name:'Taco',servings:4,ingredients:[['Kjøttdeig',400,'g'],['Løk',1,'stk'],['Tacokrydder',1,'pose'],['Tortilla',1,'pakke'],['Mais',1,'boks'],['Salsa',1,'glass']],instructions:'Stek kjøttdeig og løk. Tilsett krydder og server med tilbehør.',url:''},
{name:'Laks med poteter',servings:4,ingredients:[['Laks',600,'g'],['Poteter',1,'kg'],['Sitron',1,'stk'],['Rømme',2,'dl']],instructions:'Stek eller bak laksen. Kok poteter og server med sitron og rømme.',url:''},
{name:'Kyllinggryte',servings:4,ingredients:[['Kylling',600,'g'],['Løk',1,'stk'],['Paprika',1,'stk'],['Kokosmelk',1,'boks'],['Ris',300,'g']],instructions:'Stek kylling og grønnsaker. Tilsett kokosmelk og la gryten småkoke. Server med ris.',url:''},
{name:'Hjemmelaget pizza',servings:4,ingredients:[['Pizzabunn',1,'stk'],['Pizzasaus',1,'glass'],['Ost',300,'g'],['Skinke',200,'g']],instructions:'Fordel saus og topping på bunnen. Stek til osten er gyllen.',url:''},
{name:'Fiskekaker med poteter',servings:4,ingredients:[['Fiskekaker',8,'stk'],['Poteter',1,'kg'],['Gulrøtter',4,'stk'],['Smør',50,'g']],instructions:'Kok poteter og gulrøtter. Stek fiskekakene og server med smør.',url:''}
];
const starterPantry=['Mel','Sukker','Salt','Pepper','Olje','Smør','Kaffe','Ris','Pasta','Havregryn','Ketchup','Oppvaskmiddel','Toalettpapir'].map(name=>({name,low:false}));
let data=load(); let page='week';
function load(){try{let x=JSON.parse(localStorage.getItem(KEY));if(x)return x}catch(e){}return{week:Array(7).fill(null),recipes:starterRecipes,pantry:starterPantry,shopping:[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){document.getElementById('app').innerHTML=`<div class="app"><header class="top"><div><div class="brand">🍲 Familiemat</div><div class="subtitle">Middag, basisvarer og handleliste samlet.</div></div></header><main class="content">${page==='week'?weekView():page==='recipes'?recipesView():page==='shopping'?shoppingView():pantryView()}</main><nav class="nav"><div class="navinner">${nav('week','🏠','Uke')}${nav('recipes','🍝','Oppskrifter')}${nav('shopping','🛒','Handleliste')}${nav('pantry','🧺','Basisvarer')}</div></nav></div>`}
function nav(p,i,t){return `<button class="${page===p?'active':''}" onclick="go('${p}')"><span class="ico">${i}</span>${t}</button>`}
function go(p){page=p;render();window.scrollTo(0,0)}
function weekView(){return `<div class="section-title">Denne uka</div>${data.week.map((r,i)=>`<div class="card day"><div class="dayname">${days[i]}</div>${r?`<div class="meal"><strong>${esc(r)}</strong><small>${esc(data.recipes.find(x=>x.name===r)?.servings||4)} porsjoner</small></div><button class="btn secondary" onclick="choose(${i})">Bytt</button>`:`<div class="meal"><strong>Ingen middag valgt</strong><small>Hva skal dere spise?</small></div><button class="btn" onclick="choose(${i})">Velg</button>`}</div>`).join('')}<button class="btn full" onclick="buildShopping()">🛒 Lag handleliste fra uka</button><div class="card"><strong>Tips</strong><p class="small">Handlelisten slår sammen like ingredienser fra alle middagene. Basisvarer du markerer som «går tom» blir også lagt til.</p></div>`}
function recipesView(){return `<div class="section-title">Oppskrifter</div><button class="btn full" onclick="newRecipe()">＋ Ny oppskrift</button><button class="btn full secondary" onclick="webRecipe()">🌐 Oppskrift fra nett</button>${data.recipes.map((r,i)=>`<div class="card"><div class="recipe-head"><div><div class="recipe-title">${esc(r.name)}</div><div class="small">${r.servings} porsjoner</div></div>${r.url?`<a class="pill" href="${esc(r.url)}" target="_blank">Nettlenke</a>`:''}</div><ul class="ingredients">${r.ingredients.map(x=>`<li>${esc(x[1])} ${esc(x[2])} ${esc(x[0])}</li>`).join('')}</ul><div class="actions"><button class="btn" onclick="addRecipeToWeek(${i})">＋ Legg til i uka</button><button class="btn secondary" onclick="editRecipe(${i})">Rediger</button><button class="btn ghost" onclick="deleteRecipe(${i})">Slett</button></div></div>`).join('')}`}
function shoppingView(){const items=data.shopping;let bought=items.filter(x=>x.done).length;const groups={};items.forEach((x,i)=>{const cat=x.category||categorizeIngredient(x.name);if(!groups[cat])groups[cat]=[];groups[cat].push({...x,index:i})});const categoryOrder=['Frukt og grønt','Kjøtt og fisk','Meieri og egg','Brød og bakervarer','Tørrvarer','Hermetikk og sauser','Frysevarer','Drikke','Husholdning','Annet'];const ordered=Object.keys(groups).sort((a,b)=>categoryOrder.indexOf(a)-categoryOrder.indexOf(b));return `<div class="section-title">Handleliste</div><div class="card"><strong>${bought} av ${items.length} varer kjøpt</strong><div class="progress" style="margin-top:10px"><div style="width:${items.length?bought/items.length*100:0}%"></div></div><p class="small" style="margin-bottom:0">Sortert etter butikkategori og alfabetisk.</p></div>${items.length?ordered.map(cat=>`<div class="shop-category"><h3>${esc(cat)}</h3><div class="list">${groups[cat].map(x=>`<label class="row ${x.done?'done':''}"><input type="checkbox" ${x.done?'checked':''} onchange="toggleShop(${x.index})"><span>${esc(x.name)}</span><span class="qty">${esc(formatQty(x.qty))} ${esc(x.unit)}</span></label>`).join('')}</div></div>`).join('')+`<button class="btn full secondary" onclick="clearBought()">Fjern kjøpte varer</button>`:`<div class="empty">Handlelisten er tom.<br>Velg middager på Uke-siden og trykk «Lag handleliste».</div>`}`}
function categorizeIngredient(name){const n=name.trim().toLowerCase();if(/melk|rømme|ost|smør|yoghurt|fløte|egg|kremost|parmesan|mozzarella|feta/.test(n))return 'Meieri og egg';if(/kjøtt|kjøttdeig|kylling|skinke|bacon|pølse|laks|fisk|fiskekake|torsk|karbonade/.test(n))return 'Kjøtt og fisk';if(/potet|løk|paprika|gulrot|sitron|tomat|agurk|salat|brokkoli|blomkål|eple|banan|avokado|hvitløk|ingefær/.test(n))return 'Frukt og grønt';if(/brød|rundstykke|knekkebrød|baguette|pizzabunn/.test(n))return 'Brød og bakervarer';if(/spaghetti|pasta|ris|havre|mel|sukker|salt|pepper|olje|kaffe|te|tacokrydder|krydder|tortilla|melis|bakepulver/.test(n))return 'Tørrvarer';if(/mais|salsa|kokosmelk|bønne|hermet|glass|boks/.test(n))return 'Hermetikk og sauser';if(/frossen|is|fryse/.test(n))return 'Frysevarer';if(/juice|brus|vann|saft/.test(n))return 'Drikke';if(/toalett|dopapir|oppvask|såpe|vask|tørkepapir|serviett/.test(n))return 'Husholdning';return 'Annet'}
function pantryView(){return `<div class="section-title">Basisvarer</div><p class="small">Marker det dere begynner å gå tom for. Da havner varen automatisk på handlelisten.</p><button class="btn full" onclick="addPantry()">＋ Legg til basisvare</button><div class="list" style="margin-top:10px">${data.pantry.map((x,i)=>`<label class="row"><input type="checkbox" ${x.low?'checked':''} onchange="togglePantry(${i})"><span>${esc(x.name)}</span><span class="qty">${x.low?'Går tom':'Har hjemme'}</span></label>`).join('')}</div>`}
function choose(day){modal(`<h2>Velg middag – ${days[day]}</h2><p class="small">Trykk på en oppskrift for å legge den direkte inn på ${days[day].toLowerCase()}.</p><div class="list">${data.recipes.map((r,i)=>`<button type="button" class="row recipe-choice" onclick="setDay(${day},${i})"><span>🍽️</span><span style="flex:1;text-align:left"><strong>${esc(r.name)}</strong><small style="display:block;color:var(--muted)">${esc(r.servings)} porsjoner</small></span><span>›</span></button>`).join('')}</div><button type="button" class="btn full secondary" onclick="newRecipeForDay(${day})">＋ Lag ny oppskrift</button>`)}
function setDay(d,recipeIndex){const r=data.recipes[recipeIndex];if(!r)return;data.week[d]=r.name;save();closeModal();render()}
function addRecipeToWeek(recipeIndex){const r=data.recipes[recipeIndex];if(!r)return;modal(`<h2>Legg «${esc(r.name)}» til i uka</h2><p class="small">Velg hvilken dag middagen skal være.</p><div class="list">${days.map((d,i)=>`<button type="button" class="row" style="text-align:left" onclick="setDay(${i},${recipeIndex})"><span>📅</span><strong>${d}</strong>${data.week[i]===r.name?'<span class="qty">Valgt</span>':''}</button>`).join('')}</div>`)}
function newRecipeForDay(day){closeModal();recipeForm(-1,day)}
function buildShopping(){const old=new Map(data.shopping.map(x=>[x.name.trim().toLowerCase(),x]));const map=new Map();for(const name of data.week.filter(Boolean)){const r=data.recipes.find(x=>x.name===name);if(!r)continue;for(const [ing,q,u] of r.ingredients){const k=ing.trim().toLowerCase();if(!map.has(k))map.set(k,{name:ing,qty:0,unit:u,category:categorizeIngredient(ing),done:old.get(k)?.done||false});const x=map.get(k);if(x.unit===u&&typeof q==='number')x.qty+=q;else if(x.qty===0){x.qty=q;x.unit=u}}}for(const p of data.pantry.filter(x=>x.low)){const k=p.name.trim().toLowerCase();if(!map.has(k))map.set(k,{name:p.name,qty:1,unit:'stk',category:categorizeIngredient(p.name),done:old.get(k)?.done||false})}const order=['Frukt og grønt','Kjøtt og fisk','Meieri og egg','Brød og bakervarer','Tørrvarer','Hermetikk og sauser','Frysevarer','Drikke','Husholdning','Annet'];data.shopping=[...map.values()].sort((a,b)=>{const ca=order.indexOf(a.category),cb=order.indexOf(b.category);return (ca-cb)||a.name.localeCompare(b.name,'nb',{sensitivity:'base'})});save();page='shopping';render()}
function formatQty(q){return Number.isInteger(q)?q:String(Math.round(q*100)/100)}
function toggleShop(i){data.shopping[i].done=!data.shopping[i].done;const item=data.shopping[i];const pantry=data.pantry.find(p=>p.name.trim().toLowerCase()===item.name.trim().toLowerCase());if(pantry&&item.done)pantry.low=false;save();render()}
function clearBought(){data.shopping=data.shopping.filter(x=>!x.done);save();render()}
function togglePantry(i){data.pantry[i].low=!data.pantry[i].low;save();render()}
function addPantry(){modal(`<h2>Ny basisvare</h2><div class="field"><label>Navn</label><input id="pname" placeholder="F.eks. melk"></div><button class="btn full" onclick="savePantry()">Legg til</button>`)}
function savePantry(){let n=document.getElementById('pname').value.trim();if(!n)return;data.pantry.push({name:n,low:false});save();closeModal();render()}
function recipeForm(i=-1,day=null){const r=i>=0?data.recipes[i]:{name:'',servings:4,ingredients:[['',1,'stk']],instructions:'',url:''};modal(`<h2>${i>=0?'Rediger oppskrift':'Ny oppskrift'}</h2><div class="field"><label>Navn</label><input id="rname" value="${esc(r.name)}"></div><div class="field"><label>Porsjoner</label><input id="rserv" type="number" value="${r.servings}"></div><div class="field"><label>Ingredienser</label><div id="ings">${r.ingredients.map((x,j)=>ingRow(x,j)).join('')}</div><button class="btn secondary" onclick="addIng()">＋ Ingrediens</button></div><div class="field"><label>Fremgangsmåte</label><textarea id="rinst" rows="4">${esc(r.instructions)}</textarea></div><div class="field"><label>Lenke (valgfritt)</label><input id="rurl" type="url" value="${esc(r.url)}" placeholder="https://..."></div><button class="btn full" onclick="saveRecipe(${i},${day===null?'null':day})">Lagre oppskrift</button>`)}
function ingRow(x,j){return `<div class="ingredient-edit" data-i="${j}"><input class="in" value="${esc(x[0])}" placeholder="Vare"><input class="iq" type="number" step="0.01" value="${x[1]}"><input class="iu" value="${esc(x[2])}" placeholder="enhet"><button class="btn danger" onclick="this.parentElement.remove()">×</button></div>`}
function addIng(){document.getElementById('ings').insertAdjacentHTML('beforeend',ingRow(['',1,'stk'],Date.now()))}
function saveRecipe(i,day=null){const ings=[...document.querySelectorAll('#ings .ingredient-edit')].map(el=>[el.querySelector('.in').value.trim(),Number(el.querySelector('.iq').value)||0,el.querySelector('.iu').value.trim()]).filter(x=>x[0]);const r={name:document.getElementById('rname').value.trim(),servings:Number(document.getElementById('rserv').value)||4,ingredients:ings,instructions:document.getElementById('rinst').value,url:document.getElementById('rurl').value.trim()};if(!r.name||!ings.length)return alert('Fyll inn navn og minst én ingrediens.');if(i<0){data.recipes.push(r);if(day!==null)data.week[day]=r.name}else data.recipes[i]=r;save();closeModal();render()}
function newRecipe(){recipeForm()};function editRecipe(i){recipeForm(i)}
function deleteRecipe(i){if(confirm('Slette oppskriften?')){data.recipes.splice(i,1);data.week=data.week.map(x=>data.recipes.some(r=>r.name===x)?x:null);save();render()}}
function webRecipe(){modal(`<h2>Oppskrift fra nett</h2><p class="small">I første versjon lagrer vi lenken sammen med oppskriften. Ingrediensene legges inn manuelt, så du slipper at nettsider blokkerer import.</p><div class="field"><label>Navn</label><input id="rname" placeholder="F.eks. Lasagne"></div><div class="field"><label>Lenke</label><input id="rurl" type="url" placeholder="https://..."></div><div class="field"><label>Porsjoner</label><input id="rserv" type="number" value="4"></div><div class="field"><label>Ingredienser</label><div id="ings">${ingRow(['',1,'stk'],0)}</div><button class="btn secondary" onclick="addIng()">＋ Ingrediens</button></div><div class="field"><label>Fremgangsmåte</label><textarea id="rinst" rows="4"></textarea></div><button class="btn full" onclick="saveRecipe(-1)">Lagre oppskrift</button>`)}
function modal(inner){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal" onclick="if(event.target.id==='modal')closeModal()"><div class="sheet">${inner}<button class="btn full secondary" onclick="closeModal()">Avbryt</button></div></div>`)}
function closeModal(){document.getElementById('modal')?.remove()}
window.go=go;window.choose=choose;window.setDay=setDay;window.addRecipeToWeek=addRecipeToWeek;window.newRecipeForDay=newRecipeForDay;window.buildShopping=buildShopping;window.toggleShop=toggleShop;window.clearBought=clearBought;window.togglePantry=togglePantry;window.addPantry=addPantry;window.savePantry=savePantry;window.newRecipe=newRecipe;window.editRecipe=editRecipe;window.deleteRecipe=deleteRecipe;window.webRecipe=webRecipe;window.recipeForm=recipeForm;window.addIng=addIng;window.saveRecipe=saveRecipe;window.closeModal=closeModal;
if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});render();
